### ISSUE TITLE
Chords

### ISSUE THREAD

**Issue by cnoorman** [SammyIAm/Moppy2#38]
What is happening with multiple notes at the same time (chords) within a single midi channel? Is there a way to separate these notes over different sub channels?
Thanks -- Chris

**Comment by SammyIAm** [comment]
Unfortunately, if multiple note events come through on the same channel, there's no additional information to differentiate those notes.  That is, there's no reliable way to e.g. always have the lowest note assigned to one drive and the highest to another.  By default, each note will just immediately override the other, and you'll get one (sorta randomly selected) note of the chord.

The best generic solution I've come up with is sending incoming notes round-robin to the available drives (there's an example of this already implemented if you selected "Round Robin" from the SubAddress scripts dropdown for that channel's mapper (on the lower part of the GUI)).  Basically each incoming note will be played on the next available drive (1->2->3...->8->1->2...), and any note-off events will turn off any drives currently playing that note (since there's no way to tell for sure which note-on event the note-off event correlates to).  You can see the implementation of `nextRoundRobinSubAddress` in [this file](https://github.com/SammyIAm/Moppy2/blob/master/Java/MoppyLib/src/main/java/com/moppy/core/events/mapper/MIDIScriptMapper.java).

The upside with this strategy is that every note of a chord (up to the number of drives you have) will get played simultaneously.  The downside is that the drives don't have the same sort of consistency as with assigned SubAddresses so the notes sort of chase eachother around the setup (which I guess can be kind of fun too).

In **theory** it should be possible to use track information to separate notes as well (though this diverges a bit from the chord question), and I've got issue #9 open to track that, but it's a tricky one.

If you decide to try to implement something new, I'm happy to provide any advice that would be helpful.  Good luck!
