### ISSUE TITLE
bat file not opening

### ISSUE THREAD

**Issue by pooman2** [SammyIAm/Moppy2#74]
when i open MoppyControlGUI.bat nothing happens... i have the newest version of jdk

**Comment by SammyIAm** [comment]
Instead of double clicking on the bat (which generally should work fine), try executing the bat from a command prompt and taking a look at the output to see if there are any useful errors there.

Additionally, if there's a moppy_control_gui.log file in the bin directory, it might contain some useful errors (if the log file is non-existant, that's a useful datapoint as well)

**Comment by pooman2** [comment]
I tried downloading older versions of Jdk and I got it working on jdk 8

**Comment by pooman2** [comment]
Thx for the reply
